services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    deploy:
      resources:
        limits:
          memory: 256M   # Set memory limit to 256 MB
          cpus: "0.5"    # Limit to 0.5 CPU
        reservations:
          memory: 128M   # Request 128 MB memory
          cpus: "0.25"   # Reserve 0.25 CPU
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper

  create-topics:
    image: confluentinc/cp-kafka:latest
    container_name: create-topics
    depends_on:
      - kafka
    entrypoint: >
      sh -c "
      while ! nc -z kafka 9092; do
        echo 'Waiting for Kafka to be ready...';
        sleep 2;
      done;
      echo 'Kafka is ready!';
      /usr/bin/kafka-topics --create --topic test-topic
      --bootstrap-server kafka:9092
      --replication-factor 1
      --partitions 1
      "
